// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: first.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace First {

  /// <summary>Holder for reflection information generated from first.proto</summary>
  public static partial class FirstReflection {

    #region Descriptor
    /// <summary>File descriptor for first.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static FirstReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "CgtmaXJzdC5wcm90bxIFZmlyc3QiXAoHUmVxdWVzdBIOCgZhY3Rpb24YASAB",
            "KAkSDAoEbW9kZRgCIAEoDRIKCgJwdBgDIAEoBRIMCgRzb3J0GAQgASgNEg0K",
            "BWtlZXBMGAUgASgNEgoKAmRjGAYgASgNIpsDCghSZXNwb25zZRIOCgZhY3Rp",
            "b24YASABKAkSDAoEbWVudRgCIAMoDRINCgVpbmRleBgDIAMoDRIiCgRkYXRh",
            "GAQgAygLMhQuZmlyc3QuUmVzcG9uc2UuRGF0YRIOCgZhbE1lbnUYBSADKA0S",
            "JgoGYWxEYXRhGAYgASgLMhYuZmlyc3QuUmVzcG9uc2UuQWxkYXRhEgoKAmRj",
            "GAcgASgNGjoKBFNjaHQSCwoDdG5BGAEgASgJEgsKA3RuQhgCIAEoCRILCgN0",
            "Y0EYAyABKAkSCwoDdGNCGAQgASgJGqcBCgREYXRhEg0KBXNjaElkGAEgASgN",
            "EgwKBG1vZGUYAiABKA0SCgoCcHQYAyABKA0SDgoGcGVvcGxlGAQgASgNEiIK",
            "BHNjaFQYBSABKAsyFC5maXJzdC5SZXNwb25zZS5TY2h0Eg4KBmxpdmVJZBgG",
            "IAEoDRIQCghsaXZlTmFtZRgHIAEoCRIQCghsaXZlTGFuZxgIIAEoCRIOCgZh",
            "bE5hbWUYCSABKAkaFAoGQWxkYXRhEgoKAnB0GAEgAygJYgZwcm90bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::First.Request), global::First.Request.Parser, new[]{ "Action", "Mode", "Pt", "Sort", "KeepL", "Dc" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::First.Response), global::First.Response.Parser, new[]{ "Action", "Menu", "Index", "Data", "AlMenu", "AlData", "Dc" }, null, null, null, new pbr::GeneratedClrTypeInfo[] { new pbr::GeneratedClrTypeInfo(typeof(global::First.Response.Types.Scht), global::First.Response.Types.Scht.Parser, new[]{ "TnA", "TnB", "TcA", "TcB" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::First.Response.Types.Data), global::First.Response.Types.Data.Parser, new[]{ "SchId", "Mode", "Pt", "People", "SchT", "LiveId", "LiveName", "LiveLang", "AlName" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::First.Response.Types.Aldata), global::First.Response.Types.Aldata.Parser, new[]{ "Pt" }, null, null, null, null)})
          }));
    }
    #endregion

  }
  #region Messages
  public sealed partial class Request : pb::IMessage<Request>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<Request> _parser = new pb::MessageParser<Request>(() => new Request());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<Request> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::First.FirstReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Request() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Request(Request other) : this() {
      action_ = other.action_;
      mode_ = other.mode_;
      pt_ = other.pt_;
      sort_ = other.sort_;
      keepL_ = other.keepL_;
      dc_ = other.dc_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Request Clone() {
      return new Request(this);
    }

    /// <summary>Field number for the "action" field.</summary>
    public const int ActionFieldNumber = 1;
    private string action_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Action {
      get { return action_; }
      set {
        action_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "mode" field.</summary>
    public const int ModeFieldNumber = 2;
    private uint mode_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint Mode {
      get { return mode_; }
      set {
        mode_ = value;
      }
    }

    /// <summary>Field number for the "pt" field.</summary>
    public const int PtFieldNumber = 3;
    private int pt_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int Pt {
      get { return pt_; }
      set {
        pt_ = value;
      }
    }

    /// <summary>Field number for the "sort" field.</summary>
    public const int SortFieldNumber = 4;
    private uint sort_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint Sort {
      get { return sort_; }
      set {
        sort_ = value;
      }
    }

    /// <summary>Field number for the "keepL" field.</summary>
    public const int KeepLFieldNumber = 5;
    private uint keepL_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint KeepL {
      get { return keepL_; }
      set {
        keepL_ = value;
      }
    }

    /// <summary>Field number for the "dc" field.</summary>
    public const int DcFieldNumber = 6;
    private uint dc_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint Dc {
      get { return dc_; }
      set {
        dc_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as Request);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(Request other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Action != other.Action) return false;
      if (Mode != other.Mode) return false;
      if (Pt != other.Pt) return false;
      if (Sort != other.Sort) return false;
      if (KeepL != other.KeepL) return false;
      if (Dc != other.Dc) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (Action.Length != 0) hash ^= Action.GetHashCode();
      if (Mode != 0) hash ^= Mode.GetHashCode();
      if (Pt != 0) hash ^= Pt.GetHashCode();
      if (Sort != 0) hash ^= Sort.GetHashCode();
      if (KeepL != 0) hash ^= KeepL.GetHashCode();
      if (Dc != 0) hash ^= Dc.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Action.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Action);
      }
      if (Mode != 0) {
        output.WriteRawTag(16);
        output.WriteUInt32(Mode);
      }
      if (Pt != 0) {
        output.WriteRawTag(24);
        output.WriteInt32(Pt);
      }
      if (Sort != 0) {
        output.WriteRawTag(32);
        output.WriteUInt32(Sort);
      }
      if (KeepL != 0) {
        output.WriteRawTag(40);
        output.WriteUInt32(KeepL);
      }
      if (Dc != 0) {
        output.WriteRawTag(48);
        output.WriteUInt32(Dc);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Action.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Action);
      }
      if (Mode != 0) {
        output.WriteRawTag(16);
        output.WriteUInt32(Mode);
      }
      if (Pt != 0) {
        output.WriteRawTag(24);
        output.WriteInt32(Pt);
      }
      if (Sort != 0) {
        output.WriteRawTag(32);
        output.WriteUInt32(Sort);
      }
      if (KeepL != 0) {
        output.WriteRawTag(40);
        output.WriteUInt32(KeepL);
      }
      if (Dc != 0) {
        output.WriteRawTag(48);
        output.WriteUInt32(Dc);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (Action.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Action);
      }
      if (Mode != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(Mode);
      }
      if (Pt != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Pt);
      }
      if (Sort != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(Sort);
      }
      if (KeepL != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(KeepL);
      }
      if (Dc != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(Dc);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(Request other) {
      if (other == null) {
        return;
      }
      if (other.Action.Length != 0) {
        Action = other.Action;
      }
      if (other.Mode != 0) {
        Mode = other.Mode;
      }
      if (other.Pt != 0) {
        Pt = other.Pt;
      }
      if (other.Sort != 0) {
        Sort = other.Sort;
      }
      if (other.KeepL != 0) {
        KeepL = other.KeepL;
      }
      if (other.Dc != 0) {
        Dc = other.Dc;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            Action = input.ReadString();
            break;
          }
          case 16: {
            Mode = input.ReadUInt32();
            break;
          }
          case 24: {
            Pt = input.ReadInt32();
            break;
          }
          case 32: {
            Sort = input.ReadUInt32();
            break;
          }
          case 40: {
            KeepL = input.ReadUInt32();
            break;
          }
          case 48: {
            Dc = input.ReadUInt32();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            Action = input.ReadString();
            break;
          }
          case 16: {
            Mode = input.ReadUInt32();
            break;
          }
          case 24: {
            Pt = input.ReadInt32();
            break;
          }
          case 32: {
            Sort = input.ReadUInt32();
            break;
          }
          case 40: {
            KeepL = input.ReadUInt32();
            break;
          }
          case 48: {
            Dc = input.ReadUInt32();
            break;
          }
        }
      }
    }
    #endif

  }

  public sealed partial class Response : pb::IMessage<Response>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<Response> _parser = new pb::MessageParser<Response>(() => new Response());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<Response> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::First.FirstReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Response() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Response(Response other) : this() {
      action_ = other.action_;
      menu_ = other.menu_.Clone();
      index_ = other.index_.Clone();
      data_ = other.data_.Clone();
      alMenu_ = other.alMenu_.Clone();
      alData_ = other.alData_ != null ? other.alData_.Clone() : null;
      dc_ = other.dc_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Response Clone() {
      return new Response(this);
    }

    /// <summary>Field number for the "action" field.</summary>
    public const int ActionFieldNumber = 1;
    private string action_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Action {
      get { return action_; }
      set {
        action_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "menu" field.</summary>
    public const int MenuFieldNumber = 2;
    private static readonly pb::FieldCodec<uint> _repeated_menu_codec
        = pb::FieldCodec.ForUInt32(18);
    private readonly pbc::RepeatedField<uint> menu_ = new pbc::RepeatedField<uint>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<uint> Menu {
      get { return menu_; }
    }

    /// <summary>Field number for the "index" field.</summary>
    public const int IndexFieldNumber = 3;
    private static readonly pb::FieldCodec<uint> _repeated_index_codec
        = pb::FieldCodec.ForUInt32(26);
    private readonly pbc::RepeatedField<uint> index_ = new pbc::RepeatedField<uint>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<uint> Index {
      get { return index_; }
    }

    /// <summary>Field number for the "data" field.</summary>
    public const int DataFieldNumber = 4;
    private static readonly pb::FieldCodec<global::First.Response.Types.Data> _repeated_data_codec
        = pb::FieldCodec.ForMessage(34, global::First.Response.Types.Data.Parser);
    private readonly pbc::RepeatedField<global::First.Response.Types.Data> data_ = new pbc::RepeatedField<global::First.Response.Types.Data>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<global::First.Response.Types.Data> Data {
      get { return data_; }
    }

    /// <summary>Field number for the "alMenu" field.</summary>
    public const int AlMenuFieldNumber = 5;
    private static readonly pb::FieldCodec<uint> _repeated_alMenu_codec
        = pb::FieldCodec.ForUInt32(42);
    private readonly pbc::RepeatedField<uint> alMenu_ = new pbc::RepeatedField<uint>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<uint> AlMenu {
      get { return alMenu_; }
    }

    /// <summary>Field number for the "alData" field.</summary>
    public const int AlDataFieldNumber = 6;
    private global::First.Response.Types.Aldata alData_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::First.Response.Types.Aldata AlData {
      get { return alData_; }
      set {
        alData_ = value;
      }
    }

    /// <summary>Field number for the "dc" field.</summary>
    public const int DcFieldNumber = 7;
    private uint dc_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint Dc {
      get { return dc_; }
      set {
        dc_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as Response);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(Response other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Action != other.Action) return false;
      if(!menu_.Equals(other.menu_)) return false;
      if(!index_.Equals(other.index_)) return false;
      if(!data_.Equals(other.data_)) return false;
      if(!alMenu_.Equals(other.alMenu_)) return false;
      if (!object.Equals(AlData, other.AlData)) return false;
      if (Dc != other.Dc) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (Action.Length != 0) hash ^= Action.GetHashCode();
      hash ^= menu_.GetHashCode();
      hash ^= index_.GetHashCode();
      hash ^= data_.GetHashCode();
      hash ^= alMenu_.GetHashCode();
      if (alData_ != null) hash ^= AlData.GetHashCode();
      if (Dc != 0) hash ^= Dc.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Action.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Action);
      }
      menu_.WriteTo(output, _repeated_menu_codec);
      index_.WriteTo(output, _repeated_index_codec);
      data_.WriteTo(output, _repeated_data_codec);
      alMenu_.WriteTo(output, _repeated_alMenu_codec);
      if (alData_ != null) {
        output.WriteRawTag(50);
        output.WriteMessage(AlData);
      }
      if (Dc != 0) {
        output.WriteRawTag(56);
        output.WriteUInt32(Dc);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Action.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Action);
      }
      menu_.WriteTo(ref output, _repeated_menu_codec);
      index_.WriteTo(ref output, _repeated_index_codec);
      data_.WriteTo(ref output, _repeated_data_codec);
      alMenu_.WriteTo(ref output, _repeated_alMenu_codec);
      if (alData_ != null) {
        output.WriteRawTag(50);
        output.WriteMessage(AlData);
      }
      if (Dc != 0) {
        output.WriteRawTag(56);
        output.WriteUInt32(Dc);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (Action.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Action);
      }
      size += menu_.CalculateSize(_repeated_menu_codec);
      size += index_.CalculateSize(_repeated_index_codec);
      size += data_.CalculateSize(_repeated_data_codec);
      size += alMenu_.CalculateSize(_repeated_alMenu_codec);
      if (alData_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(AlData);
      }
      if (Dc != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(Dc);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(Response other) {
      if (other == null) {
        return;
      }
      if (other.Action.Length != 0) {
        Action = other.Action;
      }
      menu_.Add(other.menu_);
      index_.Add(other.index_);
      data_.Add(other.data_);
      alMenu_.Add(other.alMenu_);
      if (other.alData_ != null) {
        if (alData_ == null) {
          AlData = new global::First.Response.Types.Aldata();
        }
        AlData.MergeFrom(other.AlData);
      }
      if (other.Dc != 0) {
        Dc = other.Dc;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            Action = input.ReadString();
            break;
          }
          case 18:
          case 16: {
            menu_.AddEntriesFrom(input, _repeated_menu_codec);
            break;
          }
          case 26:
          case 24: {
            index_.AddEntriesFrom(input, _repeated_index_codec);
            break;
          }
          case 34: {
            data_.AddEntriesFrom(input, _repeated_data_codec);
            break;
          }
          case 42:
          case 40: {
            alMenu_.AddEntriesFrom(input, _repeated_alMenu_codec);
            break;
          }
          case 50: {
            if (alData_ == null) {
              AlData = new global::First.Response.Types.Aldata();
            }
            input.ReadMessage(AlData);
            break;
          }
          case 56: {
            Dc = input.ReadUInt32();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            Action = input.ReadString();
            break;
          }
          case 18:
          case 16: {
            menu_.AddEntriesFrom(ref input, _repeated_menu_codec);
            break;
          }
          case 26:
          case 24: {
            index_.AddEntriesFrom(ref input, _repeated_index_codec);
            break;
          }
          case 34: {
            data_.AddEntriesFrom(ref input, _repeated_data_codec);
            break;
          }
          case 42:
          case 40: {
            alMenu_.AddEntriesFrom(ref input, _repeated_alMenu_codec);
            break;
          }
          case 50: {
            if (alData_ == null) {
              AlData = new global::First.Response.Types.Aldata();
            }
            input.ReadMessage(AlData);
            break;
          }
          case 56: {
            Dc = input.ReadUInt32();
            break;
          }
        }
      }
    }
    #endif

    #region Nested types
    /// <summary>Container for nested types declared in the Response message type.</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static partial class Types {
      public sealed partial class Scht : pb::IMessage<Scht>
      #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
          , pb::IBufferMessage
      #endif
      {
        private static readonly pb::MessageParser<Scht> _parser = new pb::MessageParser<Scht>(() => new Scht());
        private pb::UnknownFieldSet _unknownFields;
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public static pb::MessageParser<Scht> Parser { get { return _parser; } }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public static pbr::MessageDescriptor Descriptor {
          get { return global::First.Response.Descriptor.NestedTypes[0]; }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        pbr::MessageDescriptor pb::IMessage.Descriptor {
          get { return Descriptor; }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public Scht() {
          OnConstruction();
        }

        partial void OnConstruction();

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public Scht(Scht other) : this() {
          tnA_ = other.tnA_;
          tnB_ = other.tnB_;
          tcA_ = other.tcA_;
          tcB_ = other.tcB_;
          _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public Scht Clone() {
          return new Scht(this);
        }

        /// <summary>Field number for the "tnA" field.</summary>
        public const int TnAFieldNumber = 1;
        private string tnA_ = "";
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public string TnA {
          get { return tnA_; }
          set {
            tnA_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
          }
        }

        /// <summary>Field number for the "tnB" field.</summary>
        public const int TnBFieldNumber = 2;
        private string tnB_ = "";
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public string TnB {
          get { return tnB_; }
          set {
            tnB_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
          }
        }

        /// <summary>Field number for the "tcA" field.</summary>
        public const int TcAFieldNumber = 3;
        private string tcA_ = "";
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public string TcA {
          get { return tcA_; }
          set {
            tcA_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
          }
        }

        /// <summary>Field number for the "tcB" field.</summary>
        public const int TcBFieldNumber = 4;
        private string tcB_ = "";
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public string TcB {
          get { return tcB_; }
          set {
            tcB_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
          }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public override bool Equals(object other) {
          return Equals(other as Scht);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public bool Equals(Scht other) {
          if (ReferenceEquals(other, null)) {
            return false;
          }
          if (ReferenceEquals(other, this)) {
            return true;
          }
          if (TnA != other.TnA) return false;
          if (TnB != other.TnB) return false;
          if (TcA != other.TcA) return false;
          if (TcB != other.TcB) return false;
          return Equals(_unknownFields, other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public override int GetHashCode() {
          int hash = 1;
          if (TnA.Length != 0) hash ^= TnA.GetHashCode();
          if (TnB.Length != 0) hash ^= TnB.GetHashCode();
          if (TcA.Length != 0) hash ^= TcA.GetHashCode();
          if (TcB.Length != 0) hash ^= TcB.GetHashCode();
          if (_unknownFields != null) {
            hash ^= _unknownFields.GetHashCode();
          }
          return hash;
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public override string ToString() {
          return pb::JsonFormatter.ToDiagnosticString(this);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public void WriteTo(pb::CodedOutputStream output) {
        #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
          output.WriteRawMessage(this);
        #else
          if (TnA.Length != 0) {
            output.WriteRawTag(10);
            output.WriteString(TnA);
          }
          if (TnB.Length != 0) {
            output.WriteRawTag(18);
            output.WriteString(TnB);
          }
          if (TcA.Length != 0) {
            output.WriteRawTag(26);
            output.WriteString(TcA);
          }
          if (TcB.Length != 0) {
            output.WriteRawTag(34);
            output.WriteString(TcB);
          }
          if (_unknownFields != null) {
            _unknownFields.WriteTo(output);
          }
        #endif
        }

        #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
          if (TnA.Length != 0) {
            output.WriteRawTag(10);
            output.WriteString(TnA);
          }
          if (TnB.Length != 0) {
            output.WriteRawTag(18);
            output.WriteString(TnB);
          }
          if (TcA.Length != 0) {
            output.WriteRawTag(26);
            output.WriteString(TcA);
          }
          if (TcB.Length != 0) {
            output.WriteRawTag(34);
            output.WriteString(TcB);
          }
          if (_unknownFields != null) {
            _unknownFields.WriteTo(ref output);
          }
        }
        #endif

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public int CalculateSize() {
          int size = 0;
          if (TnA.Length != 0) {
            size += 1 + pb::CodedOutputStream.ComputeStringSize(TnA);
          }
          if (TnB.Length != 0) {
            size += 1 + pb::CodedOutputStream.ComputeStringSize(TnB);
          }
          if (TcA.Length != 0) {
            size += 1 + pb::CodedOutputStream.ComputeStringSize(TcA);
          }
          if (TcB.Length != 0) {
            size += 1 + pb::CodedOutputStream.ComputeStringSize(TcB);
          }
          if (_unknownFields != null) {
            size += _unknownFields.CalculateSize();
          }
          return size;
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public void MergeFrom(Scht other) {
          if (other == null) {
            return;
          }
          if (other.TnA.Length != 0) {
            TnA = other.TnA;
          }
          if (other.TnB.Length != 0) {
            TnB = other.TnB;
          }
          if (other.TcA.Length != 0) {
            TcA = other.TcA;
          }
          if (other.TcB.Length != 0) {
            TcB = other.TcB;
          }
          _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public void MergeFrom(pb::CodedInputStream input) {
        #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
          input.ReadRawMessage(this);
        #else
          uint tag;
          while ((tag = input.ReadTag()) != 0) {
            switch(tag) {
              default:
                _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
                break;
              case 10: {
                TnA = input.ReadString();
                break;
              }
              case 18: {
                TnB = input.ReadString();
                break;
              }
              case 26: {
                TcA = input.ReadString();
                break;
              }
              case 34: {
                TcB = input.ReadString();
                break;
              }
            }
          }
        #endif
        }

        #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
          uint tag;
          while ((tag = input.ReadTag()) != 0) {
            switch(tag) {
              default:
                _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
                break;
              case 10: {
                TnA = input.ReadString();
                break;
              }
              case 18: {
                TnB = input.ReadString();
                break;
              }
              case 26: {
                TcA = input.ReadString();
                break;
              }
              case 34: {
                TcB = input.ReadString();
                break;
              }
            }
          }
        }
        #endif

      }

      public sealed partial class Data : pb::IMessage<Data>
      #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
          , pb::IBufferMessage
      #endif
      {
        private static readonly pb::MessageParser<Data> _parser = new pb::MessageParser<Data>(() => new Data());
        private pb::UnknownFieldSet _unknownFields;
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public static pb::MessageParser<Data> Parser { get { return _parser; } }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public static pbr::MessageDescriptor Descriptor {
          get { return global::First.Response.Descriptor.NestedTypes[1]; }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        pbr::MessageDescriptor pb::IMessage.Descriptor {
          get { return Descriptor; }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public Data() {
          OnConstruction();
        }

        partial void OnConstruction();

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public Data(Data other) : this() {
          schId_ = other.schId_;
          mode_ = other.mode_;
          pt_ = other.pt_;
          people_ = other.people_;
          schT_ = other.schT_ != null ? other.schT_.Clone() : null;
          liveId_ = other.liveId_;
          liveName_ = other.liveName_;
          liveLang_ = other.liveLang_;
          alName_ = other.alName_;
          _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public Data Clone() {
          return new Data(this);
        }

        /// <summary>Field number for the "schId" field.</summary>
        public const int SchIdFieldNumber = 1;
        private uint schId_;
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public uint SchId {
          get { return schId_; }
          set {
            schId_ = value;
          }
        }

        /// <summary>Field number for the "mode" field.</summary>
        public const int ModeFieldNumber = 2;
        private uint mode_;
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public uint Mode {
          get { return mode_; }
          set {
            mode_ = value;
          }
        }

        /// <summary>Field number for the "pt" field.</summary>
        public const int PtFieldNumber = 3;
        private uint pt_;
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public uint Pt {
          get { return pt_; }
          set {
            pt_ = value;
          }
        }

        /// <summary>Field number for the "people" field.</summary>
        public const int PeopleFieldNumber = 4;
        private uint people_;
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public uint People {
          get { return people_; }
          set {
            people_ = value;
          }
        }

        /// <summary>Field number for the "schT" field.</summary>
        public const int SchTFieldNumber = 5;
        private global::First.Response.Types.Scht schT_;
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public global::First.Response.Types.Scht SchT {
          get { return schT_; }
          set {
            schT_ = value;
          }
        }

        /// <summary>Field number for the "liveId" field.</summary>
        public const int LiveIdFieldNumber = 6;
        private uint liveId_;
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public uint LiveId {
          get { return liveId_; }
          set {
            liveId_ = value;
          }
        }

        /// <summary>Field number for the "liveName" field.</summary>
        public const int LiveNameFieldNumber = 7;
        private string liveName_ = "";
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public string LiveName {
          get { return liveName_; }
          set {
            liveName_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
          }
        }

        /// <summary>Field number for the "liveLang" field.</summary>
        public const int LiveLangFieldNumber = 8;
        private string liveLang_ = "";
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public string LiveLang {
          get { return liveLang_; }
          set {
            liveLang_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
          }
        }

        /// <summary>Field number for the "alName" field.</summary>
        public const int AlNameFieldNumber = 9;
        private string alName_ = "";
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public string AlName {
          get { return alName_; }
          set {
            alName_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
          }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public override bool Equals(object other) {
          return Equals(other as Data);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public bool Equals(Data other) {
          if (ReferenceEquals(other, null)) {
            return false;
          }
          if (ReferenceEquals(other, this)) {
            return true;
          }
          if (SchId != other.SchId) return false;
          if (Mode != other.Mode) return false;
          if (Pt != other.Pt) return false;
          if (People != other.People) return false;
          if (!object.Equals(SchT, other.SchT)) return false;
          if (LiveId != other.LiveId) return false;
          if (LiveName != other.LiveName) return false;
          if (LiveLang != other.LiveLang) return false;
          if (AlName != other.AlName) return false;
          return Equals(_unknownFields, other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public override int GetHashCode() {
          int hash = 1;
          if (SchId != 0) hash ^= SchId.GetHashCode();
          if (Mode != 0) hash ^= Mode.GetHashCode();
          if (Pt != 0) hash ^= Pt.GetHashCode();
          if (People != 0) hash ^= People.GetHashCode();
          if (schT_ != null) hash ^= SchT.GetHashCode();
          if (LiveId != 0) hash ^= LiveId.GetHashCode();
          if (LiveName.Length != 0) hash ^= LiveName.GetHashCode();
          if (LiveLang.Length != 0) hash ^= LiveLang.GetHashCode();
          if (AlName.Length != 0) hash ^= AlName.GetHashCode();
          if (_unknownFields != null) {
            hash ^= _unknownFields.GetHashCode();
          }
          return hash;
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public override string ToString() {
          return pb::JsonFormatter.ToDiagnosticString(this);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public void WriteTo(pb::CodedOutputStream output) {
        #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
          output.WriteRawMessage(this);
        #else
          if (SchId != 0) {
            output.WriteRawTag(8);
            output.WriteUInt32(SchId);
          }
          if (Mode != 0) {
            output.WriteRawTag(16);
            output.WriteUInt32(Mode);
          }
          if (Pt != 0) {
            output.WriteRawTag(24);
            output.WriteUInt32(Pt);
          }
          if (People != 0) {
            output.WriteRawTag(32);
            output.WriteUInt32(People);
          }
          if (schT_ != null) {
            output.WriteRawTag(42);
            output.WriteMessage(SchT);
          }
          if (LiveId != 0) {
            output.WriteRawTag(48);
            output.WriteUInt32(LiveId);
          }
          if (LiveName.Length != 0) {
            output.WriteRawTag(58);
            output.WriteString(LiveName);
          }
          if (LiveLang.Length != 0) {
            output.WriteRawTag(66);
            output.WriteString(LiveLang);
          }
          if (AlName.Length != 0) {
            output.WriteRawTag(74);
            output.WriteString(AlName);
          }
          if (_unknownFields != null) {
            _unknownFields.WriteTo(output);
          }
        #endif
        }

        #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
          if (SchId != 0) {
            output.WriteRawTag(8);
            output.WriteUInt32(SchId);
          }
          if (Mode != 0) {
            output.WriteRawTag(16);
            output.WriteUInt32(Mode);
          }
          if (Pt != 0) {
            output.WriteRawTag(24);
            output.WriteUInt32(Pt);
          }
          if (People != 0) {
            output.WriteRawTag(32);
            output.WriteUInt32(People);
          }
          if (schT_ != null) {
            output.WriteRawTag(42);
            output.WriteMessage(SchT);
          }
          if (LiveId != 0) {
            output.WriteRawTag(48);
            output.WriteUInt32(LiveId);
          }
          if (LiveName.Length != 0) {
            output.WriteRawTag(58);
            output.WriteString(LiveName);
          }
          if (LiveLang.Length != 0) {
            output.WriteRawTag(66);
            output.WriteString(LiveLang);
          }
          if (AlName.Length != 0) {
            output.WriteRawTag(74);
            output.WriteString(AlName);
          }
          if (_unknownFields != null) {
            _unknownFields.WriteTo(ref output);
          }
        }
        #endif

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public int CalculateSize() {
          int size = 0;
          if (SchId != 0) {
            size += 1 + pb::CodedOutputStream.ComputeUInt32Size(SchId);
          }
          if (Mode != 0) {
            size += 1 + pb::CodedOutputStream.ComputeUInt32Size(Mode);
          }
          if (Pt != 0) {
            size += 1 + pb::CodedOutputStream.ComputeUInt32Size(Pt);
          }
          if (People != 0) {
            size += 1 + pb::CodedOutputStream.ComputeUInt32Size(People);
          }
          if (schT_ != null) {
            size += 1 + pb::CodedOutputStream.ComputeMessageSize(SchT);
          }
          if (LiveId != 0) {
            size += 1 + pb::CodedOutputStream.ComputeUInt32Size(LiveId);
          }
          if (LiveName.Length != 0) {
            size += 1 + pb::CodedOutputStream.ComputeStringSize(LiveName);
          }
          if (LiveLang.Length != 0) {
            size += 1 + pb::CodedOutputStream.ComputeStringSize(LiveLang);
          }
          if (AlName.Length != 0) {
            size += 1 + pb::CodedOutputStream.ComputeStringSize(AlName);
          }
          if (_unknownFields != null) {
            size += _unknownFields.CalculateSize();
          }
          return size;
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public void MergeFrom(Data other) {
          if (other == null) {
            return;
          }
          if (other.SchId != 0) {
            SchId = other.SchId;
          }
          if (other.Mode != 0) {
            Mode = other.Mode;
          }
          if (other.Pt != 0) {
            Pt = other.Pt;
          }
          if (other.People != 0) {
            People = other.People;
          }
          if (other.schT_ != null) {
            if (schT_ == null) {
              SchT = new global::First.Response.Types.Scht();
            }
            SchT.MergeFrom(other.SchT);
          }
          if (other.LiveId != 0) {
            LiveId = other.LiveId;
          }
          if (other.LiveName.Length != 0) {
            LiveName = other.LiveName;
          }
          if (other.LiveLang.Length != 0) {
            LiveLang = other.LiveLang;
          }
          if (other.AlName.Length != 0) {
            AlName = other.AlName;
          }
          _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public void MergeFrom(pb::CodedInputStream input) {
        #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
          input.ReadRawMessage(this);
        #else
          uint tag;
          while ((tag = input.ReadTag()) != 0) {
            switch(tag) {
              default:
                _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
                break;
              case 8: {
                SchId = input.ReadUInt32();
                break;
              }
              case 16: {
                Mode = input.ReadUInt32();
                break;
              }
              case 24: {
                Pt = input.ReadUInt32();
                break;
              }
              case 32: {
                People = input.ReadUInt32();
                break;
              }
              case 42: {
                if (schT_ == null) {
                  SchT = new global::First.Response.Types.Scht();
                }
                input.ReadMessage(SchT);
                break;
              }
              case 48: {
                LiveId = input.ReadUInt32();
                break;
              }
              case 58: {
                LiveName = input.ReadString();
                break;
              }
              case 66: {
                LiveLang = input.ReadString();
                break;
              }
              case 74: {
                AlName = input.ReadString();
                break;
              }
            }
          }
        #endif
        }

        #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
          uint tag;
          while ((tag = input.ReadTag()) != 0) {
            switch(tag) {
              default:
                _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
                break;
              case 8: {
                SchId = input.ReadUInt32();
                break;
              }
              case 16: {
                Mode = input.ReadUInt32();
                break;
              }
              case 24: {
                Pt = input.ReadUInt32();
                break;
              }
              case 32: {
                People = input.ReadUInt32();
                break;
              }
              case 42: {
                if (schT_ == null) {
                  SchT = new global::First.Response.Types.Scht();
                }
                input.ReadMessage(SchT);
                break;
              }
              case 48: {
                LiveId = input.ReadUInt32();
                break;
              }
              case 58: {
                LiveName = input.ReadString();
                break;
              }
              case 66: {
                LiveLang = input.ReadString();
                break;
              }
              case 74: {
                AlName = input.ReadString();
                break;
              }
            }
          }
        }
        #endif

      }

      public sealed partial class Aldata : pb::IMessage<Aldata>
      #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
          , pb::IBufferMessage
      #endif
      {
        private static readonly pb::MessageParser<Aldata> _parser = new pb::MessageParser<Aldata>(() => new Aldata());
        private pb::UnknownFieldSet _unknownFields;
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public static pb::MessageParser<Aldata> Parser { get { return _parser; } }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public static pbr::MessageDescriptor Descriptor {
          get { return global::First.Response.Descriptor.NestedTypes[2]; }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        pbr::MessageDescriptor pb::IMessage.Descriptor {
          get { return Descriptor; }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public Aldata() {
          OnConstruction();
        }

        partial void OnConstruction();

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public Aldata(Aldata other) : this() {
          pt_ = other.pt_.Clone();
          _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public Aldata Clone() {
          return new Aldata(this);
        }

        /// <summary>Field number for the "pt" field.</summary>
        public const int PtFieldNumber = 1;
        private static readonly pb::FieldCodec<string> _repeated_pt_codec
            = pb::FieldCodec.ForString(10);
        private readonly pbc::RepeatedField<string> pt_ = new pbc::RepeatedField<string>();
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public pbc::RepeatedField<string> Pt {
          get { return pt_; }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public override bool Equals(object other) {
          return Equals(other as Aldata);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public bool Equals(Aldata other) {
          if (ReferenceEquals(other, null)) {
            return false;
          }
          if (ReferenceEquals(other, this)) {
            return true;
          }
          if(!pt_.Equals(other.pt_)) return false;
          return Equals(_unknownFields, other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public override int GetHashCode() {
          int hash = 1;
          hash ^= pt_.GetHashCode();
          if (_unknownFields != null) {
            hash ^= _unknownFields.GetHashCode();
          }
          return hash;
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public override string ToString() {
          return pb::JsonFormatter.ToDiagnosticString(this);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public void WriteTo(pb::CodedOutputStream output) {
        #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
          output.WriteRawMessage(this);
        #else
          pt_.WriteTo(output, _repeated_pt_codec);
          if (_unknownFields != null) {
            _unknownFields.WriteTo(output);
          }
        #endif
        }

        #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
          pt_.WriteTo(ref output, _repeated_pt_codec);
          if (_unknownFields != null) {
            _unknownFields.WriteTo(ref output);
          }
        }
        #endif

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public int CalculateSize() {
          int size = 0;
          size += pt_.CalculateSize(_repeated_pt_codec);
          if (_unknownFields != null) {
            size += _unknownFields.CalculateSize();
          }
          return size;
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public void MergeFrom(Aldata other) {
          if (other == null) {
            return;
          }
          pt_.Add(other.pt_);
          _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public void MergeFrom(pb::CodedInputStream input) {
        #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
          input.ReadRawMessage(this);
        #else
          uint tag;
          while ((tag = input.ReadTag()) != 0) {
            switch(tag) {
              default:
                _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
                break;
              case 10: {
                pt_.AddEntriesFrom(input, _repeated_pt_codec);
                break;
              }
            }
          }
        #endif
        }

        #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
          uint tag;
          while ((tag = input.ReadTag()) != 0) {
            switch(tag) {
              default:
                _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
                break;
              case 10: {
                pt_.AddEntriesFrom(ref input, _repeated_pt_codec);
                break;
              }
            }
          }
        }
        #endif

      }

    }
    #endregion

  }

  #endregion

}

#endregion Designer generated code
